name: Veracode Scheduled Static Scan  # Name of the GitHub Actions workflow

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st day of every month at midnight (UTC) (Scheduled Scan for main branch)
  push:
    branches:
      - "*"  # Triggers a scan on any branch whenever there is a push
  workflow_dispatch:  # Allows manual execution of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository so actions can access the files

      - name: Zip entire repository excluding .github/workflows
        run: |
          zip -r repo.zip . -x "*.github/workflows/*"  
          # Creates a ZIP archive of the repository while excluding workflow files

      - name: List contents of zip
        run: |
          unzip -l repo.zip  # Displays the contents of the ZIP file for debugging purposes

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: repo.zip  # Stores the ZIP file as an artifact for later retrieval
          path: repo.zip  # Path to the ZIP file

  veracode_upload_and_scan:
    # Runs only if:
    # - The workflow is triggered by a scheduled event AND it's on the main branch
    # - OR if it's triggered by a push on any branch
    if: (github.ref == 'refs/heads/main' && github.event_name == 'schedule') || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build  # Depends on the build job to complete first
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Checks out the repository for scan execution

      - name: Remove existing repo.zip
        run: |
          rm -f repo.zip  # Ensures any previous ZIP files are removed before downloading the new one

      - name: Get archive
        uses: actions/download-artifact@v4
        with:
          name: repo.zip  # Downloads the previously uploaded ZIP artifact
          path: repo.zip  # Path where the ZIP file is stored

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: ${{ github.event.repository.name }}  # Uses the repository name as the Veracode application name
          createprofile: true  # Creates a new application profile if it does not already exist in Veracode
          filepath: "repo.zip"  # Specifies the ZIP file to be uploaded and scanned
          version: ${{ github.run_id }}  # Uses the GitHub workflow run ID as the scan version
          vid: ${{ secrets.API_ID }}  # Veracode API credentials (ID)
          vkey: ${{ secrets.API_KEY }}  # Veracode API credentials (Key)
          criticality: 'Low'  # Sets the application's criticality level in Veracode
          team: "Your-Veracode-Team-Name"  # Replace with the actual Veracode team name for better access control
